### ISSUE TITLE
What's the difference between this and Python's native xattr support?

### ISSUE THREAD

**Issue by gamer191** [xattr/xattr#114]
Python supports xattr natively, according to https://docs.python.org/3/library/os.html#linux-extended-attributes. I'm curious what the differences are between this package and the native implementation?

**Comment by etrepum** [comment]
xattr supports extended attributes on macOS, Linux, Solaris and FreeBSD (currently available on Python 2.7+ and 3.6+, since May 2005).

Python's os module supports extended attributes only on Linux (available for Python 3.3+, since Sep 2012)

The APIs are not quite the same. xattr is a bit higher-level and was designed primarily to support macOS, but later added support for other platforms.
