### ISSUE TITLE
request: Windows support

### ISSUE THREAD

**Issue by eadmaster** [xattr/xattr#14]
emulate extended filesystem attributes on NTFS using [ADS](http://en.wikipedia.org/wiki/NTFS#Alternate_data_streams_.28ADS.29).
This was already implemented by https://bitbucket.org/khorn/winxattr, but the library is now discontinued...

**Comment by alexpilotti** [comment]
installing on Windows fails due to C CFFi compilation issues, although the CFFI dependency is properly installed via wheel. This simple workaround works fine:

https://github.com/cloudbase/xattr/commit/69ab3cdc8041b3d03625c7f55521eadf105daf0a

Would it be ok to just add a condition to avoid compiling CFFI in setup.py on Windows?

**Comment by etrepum** [comment]
All that does is allow you to install a broken cattle package, why is that desirable?
